# Generated by Django 4.2.7 on 2024-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the product', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the product')),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
